name: iron_fit
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: ^3.4.1
  collection: ^1.17.0
  logging: ^1.2.0
  firebase_auth: 5.3.1
  firebase_core: 3.6.0
  firebase_storage: 12.3.2
  firebase_app_check: ^0.3.1
  fl_chart: ^0.69.2
  flutter_animate: 4.5.0
  email_otp: ^2.1.2
  font_awesome_flutter: 10.7.0
  google_fonts: ^6.1.0
  google_sign_in: 6.2.1
  image_picker: 1.1.2
  shared_preferences: 2.3.2
  lottie: ^3.1.3
  flutter_paypal_payment: ^1.0.8
  flutter_dotenv: ^5.2.1
  google_mobile_ads: ^5.2.0
  glassmorphism_widgets: ^0.2.2
  flutter_local_notifications: ^18.0.1
  vibration: ^2.0.1
  pull_to_refresh: ^2.0.0
  password_strength: ^0.2.0
  video_player: ^2.9.2
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  stream_transform: ^2.1.1
  stop_watch_timer: ^3.1.1
  sign_in_with_apple: ^6.1.4
  provider: ^6.1.2
  percent_indicator: ^4.2.4
  page_transition: ^2.2.1
  mime_type: ^1.0.1
  json_path: ^0.7.5
  from_css_color: ^2.0.0
  go_router: ^14.7.2
  file_picker: ^8.3.1
  dropdown_button2: ^2.3.9
  cloud_firestore: ^5.4.4
  animate_do: ^4.2.0
  intl_phone_field: ^3.2.0
  share_plus: ^7.2.2
  flutter_staggered_animations: ^1.1.1
  mailer: ^6.4.1
  pin_code_fields: ^8.0.1
  firebase_messaging: ^15.1.3
  crypto: ^3.0.6
  flutter_hooks: ^0.21.2
  google_maps_flutter: ^2.5.3
  flutter_riverpod: ^2.4.9
  latlng: ^2.0.7
  googleapis_auth: ^2.0.0
  path: ^1.8.3
  flutter_native_splash: ^2.4.1
  glassmorphism_ui: ^0.3.0
  simple_gradient_text: ^1.3.0
  app_tracking_transparency: ^2.0.4

dependency_overrides:
  http: 1.2.2
  uuid: ^4.0.0
  win32: 5.5.1

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  image: 4.2.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffbb02"  # Background color
  color_dark: "#ffbb02"
  image: assets/images/splash.png  # Logo or image you want to display
  image_dark: assets/images/splash.png
  android: true  # Enable splash screen for Android
  ios: true  # Enable splash screen for iOS

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'
  adaptive_icon_background: '#00000000'
  adaptive_icon_foreground: 'assets/images/adaptive_foreground_icon.png'
  image_path_android: "assets/images/logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lottie/
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/pdfs/
    - assets/jsons/
    - .env
    - assets/images/logo.png
    - assets/service_account.json



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Changa
  #     fonts:
  #       - asset: fonts/font.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
